version: '2'
services:
  elasticsearch:
    image: aiztone.tech/docker/elasticsearch:2.3.4
    container_name: elasticsearch
    restart: always
    network_mode: "bridge"
    ports:
     - "9200:9200"
     - "9300:9300"
    volumes:
     - ./data:/usr/share/elasticsearch/data
